allowBuilds:
  '@parcel/watcher': false
  '@tailwindcss/oxide': false
  esbuild: false
  unrs-resolver: false
  vue-demi: false
minimumReleaseAgeExclude:
  - '@nuxt/eslint-config@1.16.0'
  - '@nuxt/eslint-plugin@1.16.0'
  - '@nuxt/eslint@1.16.0'
